colors: true

prepare-commit-msg:
  commands:
    commitlint:
      run: pnpm commitlint --edit $1

pre-commit:
  parallel: true
  commands:
    prettier:
      run: pnpm format {staged_files} && git update-index --again
      stage_fixed: true
    check:
      run: pnpm check
    test:
      run: pnpm test:ci {staged_files}

pre-push:
  parallel: true
  commands:
    check:
      run: pnpm check
#    packages-audit:
#      tags: frontend security
#      run: pnpm audit
