colors: true

prepare-commit-msg:
  commands:
    commitlint:
      run: pnpm commitlint --edit $1

pre-commit:
  parallel: false
  commands:
    format:
      glob: "src/**/*"
      run: pnpm format {staged_files} && git update-index --again
    lint:
      glob: "src/**/*"
      run: pnpm biome:ci {staged_files} && git update-index --again
    check:
      run: pnpm check
    test:
      run: pnpm test:ci {staged_files}

pre-push:
  parallel: true
  commands:
    check:
      run: pnpm check
#    packages-audit:
#      tags: frontend security
#      run: pnpm audit
