name: Playwright Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      #  config_actions:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # add pnpm
      - name: Config pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      #  setup_node:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      # config cache
      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      #  install_dependencies:
      - name: Install Dependencies
        run: NODE_ENV=ci pnpm install --frozen-lockfile --prefer-offline

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps

      - name: Start server and run tests
        run: pnpm exec start-server-and-test 'pnpm dev' $BASE_URL_TEST 'pnpm playwright test'

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
